CREATE TABLE IF NOT EXISTS warga (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    nik                 CHAR(16) UNIQUE NOT NULL,
    no_kk               CHAR(16) NOT NULL,
    nama_lengkap        VARCHAR(100) NOT NULL,
    tanggal_lahir       DATE NOT NULL,
    jenis_kelamin       CHAR(1) NOT NULL,
    alamat              TEXT NOT NULL,
    rt                  VARCHAR(5),
    rw                  VARCHAR(5),
    no_hp               VARCHAR(20),
    foto_ktp_url        TEXT,
    foto_kk_url         TEXT,
    c1_value            FLOAT8 DEFAULT 0,
    c2_value            FLOAT8 DEFAULT 0,
    c3_value            FLOAT8 DEFAULT 0,
    c4_value            FLOAT8 DEFAULT 0,
    c5_value            FLOAT8 DEFAULT 0,
    c6_value            FLOAT8 DEFAULT 0,
    c7_value            FLOAT8 DEFAULT 0,
    c8_value            FLOAT8 DEFAULT 0,
    c9_value            FLOAT8 DEFAULT 0,
    c10_value           FLOAT8 DEFAULT 0,
    c11_value           FLOAT8 DEFAULT 0,
    c12_value           FLOAT8 DEFAULT 0,
    c13_value           FLOAT8 DEFAULT 0,
    is_active           BOOLEAN DEFAULT TRUE,
    created_by          UUID REFERENCES users(id),
    deleted_at          TIMESTAMPTZ,
    created_at          TIMESTAMPTZ DEFAULT NOW(),
    updated_at          TIMESTAMPTZ DEFAULT NOW()
);
