CREATE TABLE IF NOT EXISTS warga (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    nik                 CHAR(16) UNIQUE NOT NULL,
    no_kk               CHAR(16) NOT NULL,
    nama_lengkap        VARCHAR(100) NOT NULL,
    tanggal_lahir       DATE NOT NULL,
    jenis_kelamin       CHAR(1) NOT NULL,
    alamat              TEXT NOT NULL,
    rt                  VARCHAR(5),
    rw                  VARCHAR(5),
    no_hp               VARCHAR(20),
    foto_ktp_url        TEXT,
    foto_kk_url         TEXT,
    penghasilan         BIGINT,
    jumlah_tanggungan   SMALLINT,
    kondisi_tempat      SMALLINT,
    status_kepemilikan  SMALLINT,
    akses_air           SMALLINT,
    pengeluaran_listrik BIGINT,
    pengeluaran_pangan  BIGINT,
    biaya_pendidikan    BIGINT,
    biaya_kesehatan     BIGINT,
    cicilan_hutang      BIGINT,
    tingkat_pendidikan  SMALLINT,
    status_pekerjaan    SMALLINT,
    kondisi_kesehatan   SMALLINT,
    is_active           BOOLEAN DEFAULT TRUE,
    created_by          UUID REFERENCES users(id),
    deleted_at          TIMESTAMPTZ,
    created_at          TIMESTAMPTZ DEFAULT NOW(),
    updated_at          TIMESTAMPTZ DEFAULT NOW()
);
