CREATE TABLE IF NOT EXISTS hasil_saw (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    periode_id      UUID REFERENCES periode_bansos(id),
    warga_id        UUID REFERENCES warga(id),
    nilai_vi        DECIMAL(10,6) NOT NULL,
    ranking         INT NOT NULL,
    status          VARCHAR(20) NOT NULL,
    override_oleh   UUID REFERENCES users(id),
    override_alasan TEXT,
    norm_c1  DECIMAL(8,6),
    norm_c2  DECIMAL(8,6),
    norm_c3  DECIMAL(8,6),
    norm_c4  DECIMAL(8,6),
    norm_c5  DECIMAL(8,6),
    norm_c6  DECIMAL(8,6),
    norm_c7  DECIMAL(8,6),
    norm_c8  DECIMAL(8,6),
    norm_c9  DECIMAL(8,6),
    norm_c10 DECIMAL(8,6),
    norm_c11 DECIMAL(8,6),
    norm_c12 DECIMAL(8,6),
    norm_c13 DECIMAL(8,6),
    dihitung_pada   TIMESTAMPTZ DEFAULT NOW()
);
